modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="autochangefight"
version="${file.jarVersion}"
displayName="AutoChangeFight"
authors="TeamPotato"
description='''
A Minecraft mod.
'''